health_perigon/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings #register_form
from accounts.views import partner_and_event_register,home,registerlink,partner_visibility,eventregister,eventtable,editevent,destroyevent, login_view, logout_view, contact, password_reset, contact_master, change_password, send_otp, verify_otp #existing_module_master, create_module_master, edit_module_master, destroy_module_master,addservice,addonservice,pharmacy,pharmacytable,lob,destroypharamcy,labotable,destroylaboratory,destroyemptytext,edit_laboratorytable,edit_service,edit_pharmacy,edit_labotable,laboratory
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name="home"),

    # path('register_form/',register_form, name="register_form"),
    path('contact/',contact, name="contact"),
    path('contact_master/',contact_master, name="contact_master"),

    path('password_reset/',password_reset, name="password_reset"),
    path('change_password/',change_password, name="change_password"),
    path('accounts/login/',login_view, name="login_view"),
    path('accounts/logout/',logout_view, name="logout_view"),
    path('send_otp/',send_otp, name="send_otp"),
    path('verify_otp/',verify_otp, name="verify_otp"),

    path('editevent/<int:module_id>',editevent, name="editevent"),
    path('destroyevent/<int:module_id>',destroyevent,name="destroyevent"),
    path('partner_visibility/',partner_visibility,name='partner_visibility'),
    path('eventregister/',eventregister,name="eventregister"),
    path('eventtable/',eventtable,name="eventtable"),
    path('registerlink/<int:module_id>',registerlink,name="registerlink"),
    path('partner_and_event_register/',partner_and_event_register,name="partner_and_event_register"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from .managers import CustomUserManager
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
import requests
import pytz
from django_countries.fields import CountryField
from django.core.validators import FileExtensionValidator

# def user_directory_path(instance, filename):
#     # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
#     return 'user_{0}/{1}'.format(instance.user, filename)

# def user_directory_path(instance, filename):
#     # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
#     return 'user_{0}/{1}'.format(instance.user, filename)

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()



    def __str__(self):
        return self.email





class Webregister(models.Model):
    eventtitle = models.CharField(max_length=255)
    targetaudiance = models.CharField(max_length=255)
    eventtype = models.CharField(max_length=255)
    created_on = models.DateField(null=True,blank=True)
    end_on = models.DateField(null=True,blank=True)
    Chairpersons = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    mobilenumber = models.CharField(max_length=255)
    email = models.EmailField()
    Moderatorname = models.CharField(max_length=266)
    mmobile = models.CharField(max_length=255, blank=True)
    memail = models.EmailField()
    ContactPersonanme = models.CharField(max_length=255, blank=True)
    Cmobile = models.CharField(max_length=255)
    Cemail = models.EmailField()
    organizedby = models.CharField(max_length=255)
    sponserby = models.CharField(max_length=255, blank=True)
    Registerationrequired = models.CharField(max_length=266)
    # registerationrequired = models.CharField(choices=REGISTER_CHOICES, max_length=128)
    paymentrequired = models.CharField(max_length=255, blank=True)
    partnerrequired = models.CharField(max_length=255)
    creation_link = models.URLField(max_length=255,null=True,blank=True)
    register_link = models.CharField(max_length=255,null=True,blank=True)
    streaming_link = models.CharField(max_length=255,null=True,blank=True)

    def __str__(self):
        return self.eventtitle

class Eventregisterationuser(models.Model):
    webregister = models.ForeignKey(Webregister,on_delete=models.CASCADE)
    header_eventimage = models.FileField(upload_to='images',null=True, blank=True)            #header_eventimage = models.ImageField(upload_to='images',null=True,blank=True,validators=[FileExtensionValidator(allowed_extensions=['jpeg'])])
    footer_eventimage = models.FileField(upload_to='images',null=True, blank=True)
    streaming_header = models.FileField(upload_to='images',null=True, blank=True)
    streaming_leftpanel = models.FileField(upload_to='images',null=True, blank=True)
    streaming_rightpanel = models.FileField(upload_to='images',null=True, blank=True)
    ticker_content = models.CharField(null=True, blank=True,max_length=255)
    ticker_time = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return str(self.pk)

class SecurityQuestions(models.Model):
    question = models.CharField(max_length=255, blank=True)
    answer = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.question


class Contact(models.Model):
    name = models.CharField(max_length=255, blank=True)
    phone_no = models.CharField(max_length=255, blank=True)
    email = models.EmailField(max_length=255, blank=True)
    message = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name



# class RegisterProfile(models.Model):
#     user = models.OneToOneField('CustomUser', on_delete= models.CASCADE)
#     name = models.CharField(max_length=50)
#     email = models.EmailField()
#     password = models.CharField(max_length=50)
#     confirm_password = models.CharField(max_length=50)
#
#     def __str__(self):
#         return self.email

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.forms import ModelForm
from .models import CustomUser,Webregister,Eventregisterationuser,SecurityQuestions,Contact  #RegisterProfile, ModuleMaster, ,AddOnServices,pharamcytab,Emptytext,Labour,Empty,Eventregister1
from django.core.validators import RegexValidator

from django_countries.fields import CountryField
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.fields import DateField
from django.contrib.auth.password_validation import validate_password
from django.core import validators
from accounts.validators import validate_password_digit, validate_password_uppercase,validate_pass
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError
import os

from django.contrib.auth import get_user_model
User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('email',)


class EventregisteruserForm(ModelForm):
    use_required_attribute = False
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(EventregisteruserForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['ticker_content'].required = False
        self.fields['ticker_time'].required = False

    # header_eventimage = forms.ImageField(widget=forms.FileInput, required=False)        #,validators=[header_eventimage]
    header_eventimage = forms.FileField(widget=forms.FileInput, required=False)
    footer_eventimage = forms.FileField(widget=forms.FileInput, required=False)
    streaming_header = forms.FileField(widget=forms.FileInput, required=False)
    streaming_rightpanel = forms.FileField(widget=forms.FileInput, required=False)
    streaming_leftpanel = forms.FileField(widget=forms.FileInput, required=False)
    # ticker_content = forms.CharField(widget=forms.TextInput(attrs={'required':'false'}))
    ticker_content = forms.CharField(required=False)
    ticker_time = forms.IntegerField(required=False)
    # ticker_time = forms.IntegerField(widget=forms.NumberInput(attrs={'required':'false'}))

    class Meta:
        model = Eventregisterationuser
        fields = ['header_eventimage','footer_eventimage','streaming_header','streaming_leftpanel','streaming_rightpanel','ticker_content','ticker_time']



    # def clean_header_eventimage(self,*args,**kwargs):
    #     cleaned_data = super(EventregisteruserForm, self).clean()
    #     header_eventimage = cleaned_data.get("header_eventimage")
    #     print(type(header_eventimage),"type of image")         #<class 'django.core.files.uploadedfile.InMemoryUploadedFile'> type of image
    #     # check_file_extenstion = header_eventimage.name
    #     # check = check_file_extenstion.split('.')[1]
    #     # print(check, 'check')
    #     # types = ['jpg', 'png', 'jpeg','PNG']
    #     # if check not in types:
    #     #     raise forms.ValidationError("file format is wrong.")
    #     if header_eventimage:
    #         if header_eventimage.size > 1000 * 100:            #41937
    #             print("header_eventimage.size",header_eventimage.size)
    #             raise forms.ValidationError("File is too big.")
    #
    #     return header_eventimage

    # def clean_footer_eventimagee(self, *args, **kwargs):
    #     cleaned_data = super(EventregisteruserForm, self).clean()
    #     footer_eventimage = cleaned_data.get("footer_eventimage")
    #     # check_file_extenstion = footer_eventimage.name
    #     # check = check_file_extenstion.split('.')[1]
    #     # print(check, 'check')
    #     # types = ['jpg', 'png', 'jpeg', 'PNG']
    #     # if check not in types:
    #     #     raise forms.ValidationError("file format is wrong.")
    #     if footer_eventimage:
    #         if footer_eventimage.size > 1000 * 100:
    #             print("reached froms.py")
    #             raise forms.ValidationError("File is too big.")
    #
    #     return footer_eventimage
    #
    # def clean_streaming_header(self, *args, **kwargs):
    #     cleaned_data = super(EventregisteruserForm, self).clean()
    #     streaming_header = cleaned_data.get("streaming_header")
    #     # check_file_extenstion = streaming_header.name           #its not working due to .name
    #     # check = check_file_extenstion.split('.')[1]
    #     # print(check, 'check')
    #     # types = ['jpg', 'png', 'jpeg', 'PNG']
    #     # if check not in types:
    #     #     raise forms.ValidationError("file format is wrong.")
    #     if streaming_header:
    #         if streaming_header.size > 1000 * 100:
    #             print("reached froms.py")
    #             raise forms.ValidationError("File is too big.")
    #
    #     return streaming_header
    #
    #
    #
    # def clean_streaming_rightpanel(self, *args, **kwargs):
    #     cleaned_data = super(EventregisteruserForm, self).clean()
    #     streaming_rightpanel = cleaned_data.get("streaming_rightpanel")
    #     # check_file_extenstion = streaming_rightpanel.name
    #     # check = check_file_extenstion.split('.')[1]
    #     # print(check, 'check')
    #     # types = ['jpg', 'png', 'jpeg', 'PNG']
    #     # if check not in types:
    #     #     raise forms.ValidationError("file format is wrong.")
    #     if streaming_rightpanel:
    #         if streaming_rightpanel.size > 1000 * 100:
    #             print("reached froms.py")
    #             raise forms.ValidationError("File is too big.")
    #
    #     return streaming_rightpanel
    #
    # def clean_streaming_leftpanel(self, *args, **kwargs):
    #     cleaned_data = super(EventregisteruserForm, self).clean()
    #     streaming_leftpanel = cleaned_data.get("streaming_leftpanel")
    #     # check_file_extenstion = streaming_leftpanel.name
    #     # check = check_file_extenstion.split('.')[1]
    #     # print(check, 'check')
    #     # types = ['jpg', 'png', 'jpeg', 'PNG']
    #     # if check not in types:
    #     #     raise forms.ValidationError("file format is wrong.")
    #     if streaming_leftpanel:
    #         if streaming_leftpanel.size > 1000 * 100:
    #             print("reached froms.py")
    #             raise forms.ValidationError("File is too big.")
    #
    #     return streaming_leftpanel



class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'User Name'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))


class SecurityQuestionsForm(ModelForm):
    question = forms.CharField(label='question', widget=forms.TextInput(attrs={'placeholder':'Security Question'}))
    answer = forms.CharField(label='answer', widget=forms.TextInput(attrs={'placeholder':'Answer'}))
    class Meta:
        model = SecurityQuestions
        fields = ['question','answer']

class PasswordForm(forms.Form):
    password = forms.CharField(disabled=True, widget=forms.PasswordInput(attrs={'placeholder':'New Password'}))
    password_confirm = forms.CharField(disabled=True, widget=forms.PasswordInput(attrs={'placeholder':'Re-enter Password'}))

class ContactForm(ModelForm):
    name = forms.CharField()
    phone_no = forms.CharField()
    email = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': 5, 'cols': 5}))

    class Meta:
        model = Contact
        fields = ['name','phone_no','email','message']


class PasswordVerificationForm(forms.Form):
    question = forms.ModelChoiceField(disabled=True, queryset=SecurityQuestions.objects.all(), empty_label=None, widget=forms.Select(attrs={'class':'form-control','id': 'sectxt'}))
    answer = forms.CharField(disabled=True, label='answer', widget=forms.TextInput(attrs={'placeholder':'Answer','id': 'anstxt'}))
    phone_no = forms.CharField(disabled=True,label='phone_no', widget=forms.TextInput(attrs={'placeholder':'Enter OTP','id': 'otptxt'}))

# name = models.CharField(max_length=50)
#     email1 = models.CharField()
# #     password = models.CharField(max_length=50)
# class RegisterProfileForm(forms.ModelForm):
#
#
#     # name=
#     # email=
#     password = forms.CharField(widget=forms.PasswordInput())
#     confirm_password = forms.CharField(widget=forms.PasswordInput())
#     class Meta:
#         model = RegisterProfile
#         fields = ['name','email','password','confirm_password']
#
#     def clean(self):
#         cleaned_data = super(RegisterProfileForm, self).clean()
#         password = cleaned_data.get("password")
#         confirm_password = cleaned_data.get("confirm_password")
#
#         if password != confirm_password:
#             raise forms.ValidationError(
#                 "password and confirm_password does not match"
#             )


class Eventregistertable(forms.ModelForm):
    eventtitle = forms.CharField(widget=forms.TextInput(attrs={}))
    TARGET_OPTION = (
        ('HDC', 'HDC'),
        ('Individual', 'Individual'),
        ('Both', 'Both')
    )
    targetaudiance = forms.ChoiceField(choices=TARGET_OPTION)

    EVENT_OPTION = (
        ('Webinar', 'webinar'),
        ('Conference', 'Conference'),
    )
    eventtype = forms.ChoiceField(choices=EVENT_OPTION)
    created_on = forms.DateField(widget=forms.DateInput(attrs={'id': 'datetime_from'}, format='%d/%m/%Y'),
                                 input_formats=settings.DATE_INPUT_FORMATS)
    end_on = forms.DateField(widget=forms.DateInput(attrs={'id': 'datetime_to'}, format='%d/%m/%Y'),
                                 input_formats=settings.DATE_INPUT_FORMATS)
    Chairpersons = forms.CharField(required=False)
    name = forms.CharField(widget=forms.TextInput(), required=False)

accounts/templates/Contact_Us_List.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %} Subscription Master - Contact Master {% endblock %}

{% block body %}
	<div class="main">
		<div class="col-md-12">
			<div class="content-holder">
				<div class="row">
					<div class="col-md-12 order-md-1">
						<h5 class="title-holder">Contact Us List</h5>
						<div class="row">
							<div class="col-md-12">
							    <div class="table-responsive">
									<table class="table table-bordered" id="datatable">
										<thead>
											<tr>
												<th>Name</th>
												<th>Mobile Number</th>
												<th>Email id</th>
												<th>Message </th>
											</tr>
										</thead>
										<tbody>
											{% for module in module %}
											<tr>
												<td>{{ module.name }}</td>
												<td>{{ module.phone_no }}</td>
												<td>{{ module.email }}</td>
												<td>{{ module.message }}</td>
											</tr>
											{% endfor %}
										</tbody>
									</table>
								</div>
								
                            </div>
						</div>	
				    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
    {% block javascript %}		
   <script>
   		$(function() {
		  var oTable = $('#datatable').DataTable({
		  	"lengthMenu": [[10, 25, 50, -1], [10, 15, 20,25]],
		    "pageLength": 10,
		    "iDisplayLength": -1,
		    "pagingType": "simple_numbers",
		    "lengthChange": false,
		  });
		  $("#search_name").on('keyup', function (){
		        $('#datatable').dataTable().fnFilter(this.value);
		    });

		});
    </script>	
    {% endblock %}

accounts/templates/dashboard.html
{% extends "base.html" %}
{% block body %}
	<h1>Dashboard</h1>
	<h3>Hi, {{user.username}}</h3>
	<p><a href="{% url 'logout_view' %}">Logout</a></p>
{% endblock %}

accounts/templates/forget_password.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">
    <head>
		<title>Health Perigon </title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">	
		<link rel="icon" type="image/png" href="{% static 'images/icon.png' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,200,300,400,500,600,700,800,900" >
		<link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
		<style>
		    .main {
                margin-top:28px;
				height:100%;
            }
			.login-btn{
	            margin: 0px 10px
            }
			.checkbox{
			    height: calc(1.5em + .75rem + 2px);
                width: 20px;
			}
			.input-group-text {
				display: -ms-flexbox;
				display: flex;
				-ms-flex-align: center;
				align-items: center;
				padding: .375rem .75rem;
				margin-bottom: 0;
				font-size: 1rem;
				font-weight: 400;
				line-height: 1.5;
				color: #495057;
				text-align: center;
				white-space: nowrap;
				background-color: #fff;
				border: 1px solid #fff;
				border-radius: 25px;
			}
		</style>
    </head>
    <body>	
	<div class="container">
		<div class="main">
		    <div class="row justify-content-center">
                <div class="col-md-5">
					<div class="row">
					    <div class="login-form">
							<div class="col-md-12">
								<div class="login-logo-holder">
								    <img src="{% static 'images/logo.png' %}" class="logo" alt="Health Perigon">
							    </div>
						    </div>
						    <div class="col-md-12">
								<div class="login-title-holder">
								    <h4>Forgot Password</h4>
								</div>
							</div>
							<form method="post">
							<div class="col-md-12">
								<div class="alert alert-success" id="update_success" style="display: none;">
								</div>
								<div class="alert alert-danger" id="update_error" style="display: none;">
								</div>
								<input type="submit" id="verify" name="verify" formmethod="post" style="visibility: hidden;">
							</div>
							<div class="form-group col-md-12">
                                <div class="input-group">
								    <span class="input-group-prepend">
								        <div class="input-group-text">
								            <input type="checkbox" id="secheck">
								        </div>
								    </span>
									{{ form1.question | add_class:'form-control' }}
									<span class="input-group-append">
									    <div class="input-group-text input-group-icon"><i class="fa fa-question" aria-hidden="true"></i></div>
									</span>
								</div>
							</div>
                            <div class="form-group col-md-12">
								<div class="input-group">
                                    {{ form1.answer | add_class:'form-control' }}
								    <span class="input-group-append">
										<div class="input-group-text input-group-icon"><i class="fa fa-comment" aria-hidden="true"></i></div>
									</span>
                                </div>
                            </div>
							<div class="form-group col-md-12 ">
                                <div class="input-group">
								    <span class="input-group-prepend">
								        <div class="input-group-text">
								            <input type="checkbox" id="otp">
								        </div>
								    </span>
								    {{ form1.phone_no | add_class:'form-control' }}
										<span class="input-group-append">
										    <div class="input-group-text input-group-icon"><i class="fa fa-commenting-o" aria-hidden="true"></i></div>
									</span>
								</div>
							</div>

							
							</form>
							<form method="post">
							<div class="form-group col-md-12">
							    <div class="input-group">
                                    {{ form.password | add_class:'form-control' }}
									<span class="input-group-append">
										<div class="input-group-text input-group-icon  "><i class="fa fa-key" aria-hidden="true"></i></div>
									</span>
                                </div>
                            </div>
							<div class="form-group col-md-12">
							    <div class="input-group">
                                    {{ form.password_confirm | add_class:'form-control' }}
									<span class="input-group-append">
										<div class="input-group-text input-group-icon  "><i class="fa fa-key" aria-hidden="true"></i></div>
									</span>
                                </div>
                            </div>
                            <div class="col-md-12">
								<div class="button-holder">
									<a href="{% url 'login_view' %}" class="login-btn">Cancel</a>
									<button class="login-btn" type="submit" formmethod="post" id="create" name="submit" value="submit">Update & Log In</button>
								</div>
							</div>
							</form>

                        </div>
			        </div>
			    </div>
	        </div>
	    </div>
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
	<script src="{% static 'js/popper-1.16.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
    	$('#secheck').change(function(){
		$('#sectxt , #anstxt').prop("disabled", !$(this).is(':checked'));
		});
		$('#otp').change(function(event){
		$('#otptxt').prop("disabled", !$(this).is(':checked'));
		event.preventDefault();
		$.ajax({
	          url : '{% url 'send_otp' %}',
	          type : 'GET',
	          data : {}
	        })
	        .done(function(response){ 
	        	if(response['error'] == false){
	            $("#update_error").hide();
	            $("#update_success").text(response['errorMessage']);
	            $("#update_success").show();
	          }
	          else{
	            $("#update_success").hide();
	            $("#update_error").text(response['errorMessage']);
	            $("#update_error").show(); 
	          }
	        })

	        .fail(function(){
	          $("#update_success").hide();
	          $("#update_error").text("Something Went Wrong");
	          $("#update_error").show();
	        })
	        .always(function(){
	        })
		});
		$("#verify").click(function(event){
			event.preventDefault();
			var question = $("#sectxt").val();
			var answer = $("#anstxt").val();
			var phone_no = $("#otptxt").val();
			console.log(question)
			console.log(answer)
			console.log(phone_no)
			if (phone_no == "" ){
				console.log("QUES_ASW")
			$.ajax({
	          url : '{% url 'password_reset' %}',
	          type : 'POST',
	          data : {question:question,answer:answer}
	        })
	        .done(function(response){
	          if(response['error'] == false){
	          	$("#id_password").removeAttr("disabled");
	          	$("#id_password_confirm").removeAttr("disabled");
	          	$("#sectxt").attr("disabled","disabled");
	          	$("#anstxt").attr("disabled","disabled");
	            $("#update_error").hide();
	            $("#update_success").text(response['errorMessage']);
	            $("#update_success").show();

	          }
	          else{
	            $("#update_success").hide();
	            $("#update_error").text(response['errorMessage']);
	            $("#update_error").show();

	          }
	        })
	        .fail(function(){
	          $("#update_success").hide();
	          $("#update_error").text("Something Went Wrong");
	          $("#update_error").show();
	        })
	        .always(function(){
	        })
	    }
	    else if (phone_no != ""){
	    	console.log("OTP");
	    	$.ajax({
	          url : '{% url 'verify_otp' %}',
	          type : 'POST',
	          data : {phone_no:phone_no}
	        })
	        .done(function(response){
	          if(response['error'] == false){
	          
	          	$("#id_password").removeAttr("disabled");
	          	$("#id_password_confirm").removeAttr("disabled");
	          	$("#otptxt").attr("disabled","disabled");
	            $("#update_error").hide();
	            $("#update_success").text(response['errorMessage']);
	            $("#update_success").show();

	          }
	          else{
	            $("#update_success").hide();
	            $("#update_error").text(response['errorMessage']);
	            $("#update_error").show();

	          }
	        })
	        .fail(function(){
	          $("#update_success").hide();
	          $("#update_error").text("Something Went Wrong");
	          $("#update_error").show();
	        })
	        .always(function(){
	        })
	    }
		});
		$("#create").click(function(event){
			event.preventDefault();
			var password = $("#id_password").val();
			var password_confirm = $("#id_password_confirm").val();
			//var string_question = JSON.stringify(question)
			//var string_answer = JSON.stringify(answer)
			//alert(string_question+string_answer)
			$.ajax({
	          url : '{% url 'change_password' %}',
	          type : 'POST',
	          data : {password:password,password_confirm:password_confirm}
	        })
	        .done(function(response){ //match
	        	if(response['error'] == false){
	            $("#update_error").hide();
	            $("#update_success").text(response['errorMessage']);
	            $("#update_success").show();
	            window.location.replace('{% url 'home' %}');
	          }
	          else{ //mismatch
	            $("#update_success").hide();
	            $("#update_error").text(response['errorMessage']);
	            $("#update_error").show(); 
	          }
	        })

	        .fail(function(){
	          $("#update_success").hide();
	          $("#update_error").text("Something Went Wrong");
	          $("#update_error").show();
	        })
	        .always(function(){
	        })
		});
    </script>
    </body>
</html>

accounts/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
<h1>HIIIIIIIIIIIIII</h1>
</body>
</html>